import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Package2Icon } from "@/utils/Icons/Package2Icon";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Data Duel App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-[60px] items-center justify-center border px-6 gap-2 text-white font-semibold">
          <Package2Icon className="h-6 w-6" />
          <span>NFL</span>
        </div>
        {children}
      </body>
    </html>
  );
}
