export const mockTeamData = [
  {
    id: 1,
    name: "Washington Huskies",
    teamSpread: "+4.5",
    pointsScoredPerGame: 37.6,
    netPassingYardsPerGame: 350,
    rushingYardsPerGame: 123.6,
  },
  {
    id: 2,
    name: "Michigan Wolverines",
    teamSpread: "-4.5",
    pointsScoredPerGame: 36,
    netPassingYardsPerGame: 218.9,
    rushingYardsPerGame: 159.5,
  },
];

export const mockDuelData = [
  {
    id: 1,
    name: "Washington Huskies",
    teamSpread: "+4.5",
    pointsScoredPerGame: 37.6,
    netPassingYardsPerGame: 350,
    rushingYardsPerGame: 123.6,
    players: [
      {
        id: 1,
        firstName: "Michael",
        lastName: "Penix Jr",
        team: 1,
        passingLine: "O/U 292.5",
        passingYardsPerGame: 332,
        touchdownsPerGame: 2.5,
        stats: [
          {
            id: 1001,
            player: 1,
            game: 101,
            passingYards: 430,
            touchDowns: 2,
          },
          {
            id: 1002,
            player: 1,
            game: 103,
            passingYards: 319,
            touchDowns: 1,
          },
          {
            id: 1003,
            player: 1,
            game: 104,
            passingYards: 204,
            touchDowns: 2,
          },
          {
            id: 1004,
            player: 1,
            game: 105,
            passingYards: 162,
            touchDowns: 2,
          },
          {
            id: 1005,
            player: 1,
            game: 106,
            rushingYards: 332,
            touchDowns: 2,
          },
        ],
      },
      {
        id: 2,
        firstName: "Dillon",
        lastName: "Johnson",
        team: 1,
        rushingLine: "O/U 37.5",
        rushingYardsPerGame: 89.4,
        rushingAttemptsPerGame: 17.1,
        rushingTouchdowns: 16,
        receivingTouchdowns: 0,
        odds: -110,
        stats: [
          {
            id: 1006,
            player: 2,
            game: 101,
            rushingYards: 49,
            touchDowns: 2,
            attempts: 21,
          },
          {
            id: 1007,
            player: 2,
            game: 103,
            rushingYards: 21,
            touchDowns: 2,
            attempts: 28,
          },
          {
            id: 1008,
            player: 2,
            game: 104,
            rushingYards: 82,
            touchDowns: 1,
            attempts: 21,
          },
          {
            id: 1009,
            player: 2,
            game: 105,
            rushingYards: 21,
            touchDowns: 0,
            attempts: 16,
          },
          {
            id: 1010,
            player: 2,
            game: 106,
            rushingYards: 104,
            touchDowns: 1,
            attempts: 23,
          },
        ],
      },
      {
        id: 5,
        firstName: "Tybo",
        lastName: "Rogers",
        team: 1,
        rushingLine: "O/U 19.5",
        rushingYardsPerGame: 18.2,
        rushingAttemptsPerGame: 4.3,
        stats: [
          {
            id: 1011,
            player: 5,
            game: 101,
            rushingYards: 19,
            attempts: 5,
          },
          {
            id: 1012,
            player: 5,
            game: 103,
            rushingYards: 14,
            attempts: 3,
          },
          {
            id: 1013,
            player: 5,
            game: 104,
            rushingYards: 1,
            attempts: 1,
          },
          {
            id: 1014,
            player: 5,
            game: 105,
            rushingYards: 24,
            attempts: 2,
          },
          {
            id: 1015,
            player: 5,
            game: 106,
            rushingYards: 21,
            attempts: 5,
          },
        ],
      },
      {
        id: 7,
        firstName: "Rome",
        lastName: "Odunze",
        team: 1,
        receivingLine: "O/U 89.5",
        receivingYardsPerGame: 110.9,
        receptionsPerGame: 6.2,
        rushingTouchdowns: 1,
        receivingTouchdowns: 13,
        odds: -113,
        stats: [
          {
            id: 1016,
            player: 7,
            game: 101,
            receivingYards: 125,
            touchDowns: 0,
            receptions: 6,
          },
          {
            id: 1017,
            player: 7,
            game: 103,
            receivingYards: 102,
            touchDowns: 0,
            receptions: 8,
          },
          {
            id: 1018,
            player: 7,
            game: 104,
            receivingYards: 120,
            touchDowns: 2,
            receptions: 7,
          },
          {
            id: 1019,
            player: 7,
            game: 105,
            receivingYards: 106,
            touchDowns: 2,
            receptions: 7,
          },
          {
            id: 1020,
            player: 7,
            game: 106,
            receivingYards: 111,
            touchDowns: 2,
            receptions: 3,
          },
        ],
      },
      {
        id: 8,
        firstName: "Ja'Lynn",
        lastName: "Polk",
        team: 1,
        receivingLine: "O/U 48.5",
        receivingYardsPerGame: 93.5,
        receptionsPerGame: 5.4,
        rushingTouchdowns: 1,
        receivingTouchdowns: 9,
        odds: 215,
        stats: [
          {
            id: 1021,
            player: 8,
            game: 101,
            receivingYards: 122,
            touchDowns: 1,
            receptions: 5,
          },
          {
            id: 1022,
            player: 8,
            game: 103,
            receivingYards: 57,
            touchDowns: 0,
            receptions: 5,
          },
          {
            id: 1023,
            player: 8,
            game: 104,
            receivingYards: 55,
            touchDowns: 0,
            receptions: 4,
          },
          {
            id: 1024,
            player: 8,
            game: 105,
            receivingYards: 52,
            touchDowns: 0,
            receptions: 5,
          },
          {
            id: 1025,
            player: 8,
            game: 106,
            receivingYards: 148,
            touchDowns: 1,
            receptions: 5,
          },
        ],
      },
      {
        id: 9,
        firstName: "Jalen",
        lastName: "McMillan",
        team: 1,
        receivingLine: "O/U 59.5",
        receivingYardsPerGame: 87.5,
        receptionsPerGame: 6.5,
        stats: [
          {
            id: 1026,
            player: 9,
            game: 101,
            receivingYards: 58,
            receptions: 5,
          },
          {
            id: 1027,
            player: 9,
            game: 103,
            receivingYards: 131,
            receptions: 9,
          },
          {
            id: 1028,
            player: 9,
            game: 104,
            receivingYards: 26,
            receptions: 5,
          },
          {
            id: 1029,
            player: 9,
            game: 105,
            receivingYards: 96,
            receptions: 4,
          },
          {
            id: 1030,
            player: 9,
            game: 106,
            receivingYards: 120,
            receptions: 8,
          },
        ],
      },
      {
        id: 13,
        firstName: "Jack",
        lastName: "Westover",
        team: 1,
        receivingLine: "O/U 26.5",
        receivingYardsPerGame: 27.9,
        receptionsPerGame: 2.9,
        stats: [
          {
            id: 1031,
            player: 13,
            game: 101,
            receivingYards: 59,
            receptions: 6,
          },
          {
            id: 1032,
            player: 13,
            game: 103,
            receivingYards: 4,
            receptions: 1,
          },
          {
            id: 1033,
            player: 13,
            game: 104,
            receivingYards: 25,
            receptions: 2,
          },
          {
            id: 1034,
            player: 13,
            game: 105,
            receivingYards: 43,
            receptions: 4,
          },
          {
            id: 1035,
            player: 13,
            game: 106,
            receivingYards: 64,
            receptions: 7,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Michigan Wolverines",
    teamSpread: "-4.5",
    pointsScoredPerGame: 36,
    netPassingYardsPerGame: 218.9,
    rushingYardsPerGame: 159.5,
    players: [
      {
        id: 3,
        firstName: "JJ",
        lastName: "McCarthy",
        team: 2,
        passingLine: "O/U 199.5",
        passingYardsPerGame: 203.6,
        touchdownsPerGame: 1.6,
        stats: [
          {
            id: 1036,
            player: 3,
            game: 102,
            passingYards: 221,
            touchDowns: 3,
          },
          {
            id: 1037,
            player: 3,
            game: 107,
            passingYards: 147,
            touchDowns: 0,
          },
          {
            id: 1038,
            player: 3,
            game: 108,
            passingYards: 148,
            touchDowns: 1,
          },
          {
            id: 1039,
            player: 3,
            game: 109,
            passingYards: 141,
            touchDowns: 0,
          },
          {
            id: 1040,
            player: 3,
            game: 110,
            passingYards: 60,
            touchDowns: 0,
          },
        ],
      },
      {
        id: 4,
        firstName: "Blake",
        lastName: "Corum",
        team: 2,
        rushingLine: "O/U 103.5",
        rushingYardsPerGame: 79.4,
        rushingAttemptsPerGame: 16.9,
        rushingTouchdowns: 25,
        receivingTouchdowns: 1,
        odds: -400,
        stats: [
          {
            id: 1041,
            player: 4,
            game: 102,
            rushingYards: 83,
            touchDowns: 1,
            attempts: 19,
          },
          {
            id: 1042,
            player: 4,
            game: 107,
            rushingYards: 52,
            touchDowns: 2,
            attempts: 16,
          },
          {
            id: 1043,
            player: 4,
            game: 108,
            rushingYards: 88,
            touchDowns: 2,
            attempts: 22,
          },
          {
            id: 1044,
            player: 4,
            game: 109,
            rushingYards: 94,
            touchDowns: 2,
            attempts: 28,
          },
          {
            id: 1045,
            player: 4,
            game: 110,
            rushingYards: 145,
            touchDowns: 2,
            attempts: 26,
          },
        ],
      },
      {
        id: 6,
        firstName: "Donovan",
        lastName: "Edwards",
        team: 2,
        rushingLine: "O/U 31.5",
        rushingYardsPerGame: 28,
        rushingAttemptsPerGame: 8.1,
        receivingLine: "O/U 14.5",
        receivingYardsPerGame: 17.8,
        receptionsPerGame: 2.1,
        stats: [
          {
            id: 1046,
            player: 6,
            game: 102,
            rushingYards: 11,
            receivingYards: 0,
            attempts: 4,
            receptions: 0,
          },
          {
            id: 1047,
            player: 6,
            game: 107,
            rushingYards: 28,
            receivingYards: 19,
            attempts: 4,
            receptions: 4,
          },
          {
            id: 1048,
            player: 6,
            game: 108,
            rushingYards: 31,
            receivingYards: 5,
            attempts: 10,
            receptions: 2,
          },
          {
            id: 1049,
            player: 6,
            game: 109,
            rushingYards: 39,
            receivingYards: 0,
            attempts: 11,
            receptions: 0,
          },
          {
            id: 1050,
            player: 6,
            game: 110,
            rushingYards: 52,
            receivingYards: 0,
            attempts: 10,
            receptions: 0,
          },
        ],
      },
      {
        id: 10,
        firstName: "Cornelius",
        lastName: "Johnson",
        team: 2,
        receivingLine: "O/U 39.5",
        receivingYardsPerGame: 44.5,
        receptionsPerGame: 3.4,
        stats: [
          {
            id: 1051,
            player: 10,
            game: 102,
            receivingYards: 12,
            receptions: 2,
          },
          {
            id: 1052,
            player: 10,
            game: 107,
            receivingYards: 64,
            receptions: 9,
          },
          {
            id: 1053,
            player: 10,
            game: 108,
            receivingYards: 33,
            receptions: 4,
          },
          {
            id: 1054,
            player: 10,
            game: 109,
            receivingYards: 24,
            receptions: 3,
          },
          {
            id: 1055,
            player: 10,
            game: 110,
            receivingYards: 24,
            receptions: 2,
          },
        ],
      },
      {
        id: 11,
        firstName: "Colston",
        lastName: "Loveland",
        team: 2,
        receivingLine: "O/U 35.5",
        receivingYardsPerGame: 41.8,
        receptionsPerGame: 3,
        rushingTouchdowns: 0,
        receivingTouchdowns: 4,
        odds: 245,
        stats: [
          {
            id: 1056,
            player: 11,
            game: 102,
            receivingYards: 13,
            touchDowns: 0,
            receptions: 2,
          },
          {
            id: 1057,
            player: 11,
            game: 107,
            receivingYards: 22,
            touchDowns: 0,
            receptions: 3,
          },
          {
            id: 1058,
            player: 11,
            game: 108,
            receivingYards: 88,
            touchDowns: 0,
            receptions: 5,
          },
          {
            id: 1059,
            player: 11,
            game: 109,
            receivingYards: 36,
            touchDowns: 0,
            receptions: 3,
          },
          {
            id: 1060,
            player: 11,
            game: 110,
            receivingYards: 7,
            touchDowns: 0,
            receptions: 2,
          },
        ],
      },
      {
        id: 12,
        firstName: "Roman",
        lastName: "Wilson",
        team: 2,
        receivingLine: "O/U 48.5",
        receivingYardsPerGame: 56.5,
        receptionsPerGame: 3.5,
        rushingTouchdowns: 12,
        receivingTouchdowns: 0,
        odds: 182,
        stats: [
          {
            id: 1061,
            player: 12,
            game: 102,
            receivingYards: 73,
            touchDowns: 1,
            receptions: 4,
          },
          {
            id: 1062,
            player: 12,
            game: 107,
            receivingYards: 14,
            touchDowns: 0,
            receptions: 1,
          },
          {
            id: 1063,
            player: 12,
            game: 108,
            receivingYards: 36,
            touchDowns: 1,
            receptions: 3,
          },
          {
            id: 1064,
            player: 12,
            game: 109,
            receivingYards: 23,
            touchDowns: 0,
            receptions: 1,
          },
          {
            id: 1065,
            player: 12,
            game: 110,
            receivingYards: 143,
            touchDowns: 0,
            receptions: 9,
          },
        ],
      },
    ],
  },
];
